import { jsPDF } from "jspdf";

export const useGeneratePDF = () => {
  const generatePDF = (data) => {
    const doc = new jsPDF();

    doc.setFont("Helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(40, 60, 100);
    doc.text("Event Details", 105, 15, { align: "center" });

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Name:`, 10, 30);
    doc.setFont("Helvetica", "bold");
    doc.text(data.name, 40, 30);

    doc.setFont("Helvetica", "normal");
    doc.text(`Description:`, 10, 40);
    doc.text(data.description, 40, 40);

    doc.text(`Date:`, 10, 50);
    doc.text(new Date(data.date).toLocaleDateString(), 40, 50);

    doc.text(`Location:`, 10, 60);
    doc.text(data.location, 40, 60);

    doc.setDrawColor(200, 200, 200); 
    doc.line(10, 70, 200, 70);

    doc.setFontSize(18);
    doc.setFont("Helvetica", "bold");
    doc.setTextColor(40, 60, 100);
    doc.text("Participants", 10, 80);

    doc.setFontSize(12);
    doc.setFont("Helvetica", "normal");
    doc.setTextColor(0, 0, 0);

    let y = 90;

    doc.setFillColor(230, 230, 250);
    doc.rect(10, y, 190, 8, "F");
    doc.text("No.", 12, y + 6);
    doc.text("Username", 40, y + 6);
    doc.text("Email", 120, y + 6);
    y += 10;

    data.users.forEach((user, index) => {
      if (index % 2 === 0) {
        doc.setFillColor(245, 245, 245); 
        doc.rect(10, y , 190, 8, "F");
      }
      doc.text(`${index + 1}`, 12, y+5);
      doc.text(user.username, 40, y +5 );
      doc.text(user.email, 120, y + 5);
      y += 10;

      if (y > 280) {
        doc.addPage();
        y = 10;
      }
    });

    doc.setFontSize(10);
    doc.setFont("Helvetica", "italic");
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Event Management System", 105, 290, { align: "center" });

    doc.save(`${data.name}_EventDetails.pdf`);
  };

  return { generatePDF };
};
